import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#f5f5f5',
  },
  toolbar: {
    padding: 10,
    backgroundColor: '#ffffff',
    borderBottomWidth: 1,
    borderBottomColor: '#e0e0e0',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  toolbarTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    marginRight: 15,
  },
  toolbarButtonGroup: {
    flexDirection: 'row',
    gap: 8,
  },
  toolbarButton: {
    padding: 8,
  },
  mindMapContainer: {
    flex: 1,
    padding: 20,
    overflow: 'scroll',
  },
  nodeContainer: {
    flexDirection: 'column',
    alignItems: 'flex-start',
    marginBottom: 8,
  },
  nodeRow: {
    flexDirection: 'row',
    alignItems: 'center',
    position: 'relative',
  },
  node: {
    borderRadius: 8,
    padding: 8,
    paddingHorizontal: 12,
    borderWidth: 1,
    minWidth: 120,
  },
  nodeActions: {
    flexDirection: 'row',
    marginLeft: 8,
    gap: 4,
  },
  actionButton: {
    padding: 4,
    borderRadius: 16,
  },
  childrenContainer: {
    marginLeft: 32,
    paddingLeft: 16,
    borderLeftWidth: 1,
    borderLeftColor: '#d1d5db',
    marginTop: 8,
  },
  aiSuggestionContainer: {
    backgroundColor: '#eef2ff',
    padding: 12,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#c7d2fe',
    maxWidth: 250,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 3,
    elevation: 2,
  },
  aiSuggestionTitle: {
    fontWeight: '500',
    color: '#4338ca',
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
  },
  suggestionItem: {
    fontSize: 14,
    padding: 4,
    borderRadius: 4,
    flexDirection: 'row',
    alignItems: 'center',
  },
  sidePanel: {
    width: 250,
    borderLeftWidth: 1,
    borderLeftColor: '#e0e0e0',
    backgroundColor: '#ffffff',
    padding: 16,
  },
  searchContainer: {
    flexDirection: 'row',
    marginBottom: 16,
  },
  searchInput: {
    flex: 1,
    padding: 8,
    borderWidth: 1,
    borderColor: '#e0e0e0',
    borderRightWidth: 0,
    borderTopLeftRadius: 4,
    borderBottomLeftRadius: 4,
  },
  searchButton: {
    backgroundColor: '#e5e7eb',
    padding: 8,
    borderWidth: 1,
    borderColor: '#e0e0e0',
    borderLeftWidth: 0,
    borderTopRightRadius: 4,
    borderBottomRightRadius: 4,
  },
  modalOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.3)',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 10,
  },
});
